### ISSUE TITLE
Getting an exception when trying to Jsonserialize discriminatedunion object

### ISSUE THREAD

**Issue by gaolihao** [Ne4to/N.SourceGenerators.UnionTypes#37]
Stack trace:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable convert to CompleteProgressArgs. Inner value is ProgressArgs not CompleteProgressArgs.
  Source=DiscriminatedUnionDemo
  StackTrace:
   at ProgressArgsBase.get_AsCompleteProgressArgs() in C:\Users\justu\Downloads\DiscriminatedUnionDemo 1\DiscriminatedUnionDemo\artifacts\obj\DiscriminatedUnionDemo\debug\N.SourceGenerators.UnionTypes\N.SourceGenerators.UnionTypes.UnionTypesGenerator\ProgressArgsBase.g.cs:line 65
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
```

To reproduce:
```cs
using N.SourceGenerators.UnionTypes;
using Newtonsoft.Json;

ProgressArgsBase p = new ProgressArgs(0.3);

var json = JsonConvert.SerializeObject(p);
var res = JsonConvert.DeserializeObject<ProgressArgsBase>(json);


[N.SourceGenerators.UnionTypes.UnionType(typeof(ProgressArgs), TypeDiscriminator = "Foo")]
[N.SourceGenerators.UnionTypes.UnionType(typeof(CompleteProgressArgs), TypeDiscriminator = "Boo")]
[JsonPolymorphicUnion]
public partial class ProgressArgsBase
{
}

public class ProgressArgs
{
    private double fraction;
    public ProgressArgs()
    {
    }

    public ProgressArgs(double fraction)
    {
        this.fraction = fraction;
    }
}

public class CompleteProgressArgs
{
}
```

**Comment by Ne4to** [comment]
It's supposed to work with `System.Text.Json` not `Newtonsoft.Json`
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

namespace N.SourceGenerators.UnionTypes.BehaviorTests;

[UnionType(typeof(ProgressArgs), TypeDiscriminator = "Foo")]
[UnionType(typeof(CompleteProgressArgs), TypeDiscriminator = "Boo")]
[JsonPolymorphicUnion]
public partial class ProgressArgsBase
{
}

public class ProgressArgs : IEquatable<ProgressArgs>
{
    [JsonInclude]
    private double fraction;
    public ProgressArgs()
    {
    }

    public ProgressArgs(double fraction)
    {
        this.fraction = fraction;
    }

    public bool Equals(ProgressArgs? other)
    {
        return other != null && fraction == other.fraction;
    }
}

public class CompleteProgressArgs
{
}

public class Issue37Test
{
    [Fact]
    public void FooTest()
    {
        ProgressArgsBase p = new ProgressArgs(0.3);

        var json = JsonSerializer.Serialize(p);
        var res = JsonSerializer.Deserialize<ProgressArgsBase>(json);

        Assert.Equal(p, res);
    }
}
```
